apiVersion: v1
kind: Pod
metadata:
  name: mnm-car-listing
  namespace: default
spec:
  containers:
    - image: mnm-car-listing:0.1
      name: mnm-car-listing
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8081
          hostPort: 8081