apiVersion: v1
kind: Service
metadata:
  name: mnm-car-listing
  namespace: mnm-car-recommend
spec:
  type: NodePort
  selector:
    app: mnm-car-listing
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 38081
